### ISSUE TITLE
Approvale?

### ISSUE THREAD

**Issue by Macleykun** [Kuro-Rui/Kuro-Cogs#7]
### Issue Details

Heya, i was wondering if it's possible for ya cogs to be approved :) i have no clue how the process goes, but i think people should find ya cogs easier by verifying imo!

**Comment by Kuro-Rui** [comment]
> ### Issue Details
> 
> Heya, i was wondering if it's possible for ya cogs to be approved :) i have no clue how the process goes, but i think people should find ya cogs easier by verifying imo!

I'm currently applying my cogs to be approved in the CogBoard. The process takes longer now since the Cog-Creators is working on migrating Red to dpy2 (Red 3.5)
With that, I will also migrate my cogs to dpy2 when all Red 3.5 is released to avoid anymore breaking changes (by this, I mean update at once)
Thanks for your opinion tho! :)
